### ISSUE TITLE
sender.so: undefined symbol: ruby_current_thread

### ISSUE THREAD

**Issue by sheldonh** [RidiculousPower/sender#4]
Hi there,

I'm hugely interested in the sender gem, because I need **caller** to avoid inadvertent exposure of protected methods in a dynamic proxy.

Unfortunately, when I try to load the gem under ruby-1.9.3-p194 (using RVM) on a Fedora 17 x86_64 Linux box, I get this:

``` ruby
require 'rubygems'
require 'sender'
LoadError: [...]/gems/sender-1.5.9/lib/sender.so: undefined symbol: ruby_current_thread - [...]/gems/sender-1.5.9/lib/sender.so
    from [...]/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from [...]/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from [...]/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from (irb):2
    from [...]/bin/irb:16:in `<main>'
```

Could you tell me which version of ruby the sender gem known to work on, so that I can poke around and see what's up?

As an aside, I think archive-tar-minitar is missing as a development dependency of the gem.

Thanks,
Sheldon.

**Comment by sheldonh** [comment]
This ruby pull request exposes the hidden symbol. I don't understand why it was never accepted.

https://github.com/ruby/ruby/pull/47

**Comment by Asher-** [comment]
I'll try to make some time to look into it today. Thanks for letting me know about the issue.
