### ISSUE TITLE
Gem installation requires the installation of 'minitar' gem.

### ISSUE THREAD

**Issue by burtlo** [RidiculousPower/sender#6]
``` bash
$ gem list

*** LOCAL GEMS ***

addressable (2.3.2)
bundler (1.2.1)
configuration (1.3.2)
excon (0.16.4)
heroku (2.32.9)
heroku-api (0.3.5)
launchy (0.3.7)
mime-types (1.19)
netrc (0.7.7)
open_gem (1.4.2)
rake (0.9.2.2)
rest-client (1.6.7)
rubygems-bundler (1.1.0)
rubyzip (0.9.9)
rvm (1.11.3.5)
```

``` bash
$ gem install sender
Fetching: core-source-0.2.6.gem (100%)
Fetching: mkmfmf-0.4.gem (100%)
Fetching: rake-compiler-0.8.1.gem (100%)
Fetching: sender-1.5.10.gem (100%)

Building native extensions.  This could take a while...
ERROR:  Error installing sender:
        ERROR: Failed to build gem native extension.

        /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/bin/ruby
/Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- archive/tar/minitar (LoadError)
        from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@development/gems/core-source-0.2.6/lib/core-source.rb:7:in `<top (required)>'
        from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from extconf.rb:4:in `<main>'


Gem files will remain installed in /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@development/gems/sender-1.5.10 for inspection.
Results logged to /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@development/gems/sender-1.5.10/ext/sender/gem_make.out
```
## Installing minitar gem and then installing sender

``` bash
$ gem install minitar
Fetching: minitar-0.5.3.gem (100%)
Successfully installed minitar-0.5.3
1 gem installed

$ gem install sender
Building native extensions.  This could take a while...
Successfully installed sender-1.5.10
1 gem installed
```

**Comment by Asher-** [comment]
Thanks for letting me know - core-source should have had the minitar dependency. I'm entirely unclear why it doesn't already, as I could have sworn it all worked as is. In any case, I've added it now and pushed the gem.
